// GENERATED by scripts/glyphs.mjs — do not edit: change the drawing there and run `pnpm glyphs`.
import type { Glyph } from "./glyph";

/** tip gift support creator */
export const tip: Glyph = /* @__PURE__ */ Object.freeze({ p: ["M5 9.5h14v3.5H5z","M6.5 13v6.5h11V13","M12 9.5v10","M12 9.5C10.5 6 7 5.5 7.5 8c.3 1.2 2.5 1.5 4.5 1.5","M12 9.5c1.5-3.5 5-4 4.5-1.5-.3 1.2-2.5 1.5-4.5 1.5"], n: [[12,16]] });
/** unlock open paid content */
export const unlock: Glyph = /* @__PURE__ */ Object.freeze({ p: ["M7 11H17L19 13V19L17 21H7L5 19V13Z","M8 11V7.5a4 4 0 0 1 7.7-1.5"], n: [[12,16]] });
/** paid premium ticket pass access */
export const paid: Glyph = /* @__PURE__ */ Object.freeze({ p: ["M4 7.5 6.5 5h11L20 7.5v2.5a2 2 0 0 0 0 4v2.5L17.5 19h-11L4 16.5V14a2 2 0 0 0 0-4z","M15 7.5v1.5M15 11.25v1.5M15 15v1.5"], n: [[9.75,12]] });
/** auction gavel bid escrow */
export const auction: Glyph = /* @__PURE__ */ Object.freeze({ p: ["M10.6 6.1 14.1 2.6l7.3 7.3-3.5 3.5z","M14.2 9.8 5 19","M3 21.5h9"], n: [[16,8]] });
/** challenge dare flag */
export const challenge: Glyph = /* @__PURE__ */ Object.freeze({ p: ["M6 21V4","M6 4.5h10.5l-2 3.5 2 3.5H6"], n: [[6,21]] });
/** goal target objective */
export const goal: Glyph = /* @__PURE__ */ Object.freeze({ p: ["M12 3.5V2M20.5 12H22M12 20.5V22M3.5 12H2"], c: [[12,12,8.5],[12,12,4.5]], n: [[12,12]] });
/** creator profile star user */
export const creator: Glyph = /* @__PURE__ */ Object.freeze({ p: ["M12 4.5L15.9 6.75L15.9 11.25L12 13.5L8.1 11.25L8.1 6.75Z","M4.5 20.5c1-3.5 4-5.5 7.5-5.5s6.5 2 7.5 5.5"], n: [[12,9]] });
/** story ring circle */
export const story: Glyph = /* @__PURE__ */ Object.freeze({ p: ["M16.25 4.64A8.5 8.5 0 1 1 7.75 4.64"], c: [[12,12,4.5]], n: [[16.25,4.64]] });
/** story 24h ephemeral clock expires */
export const story24h: Glyph = /* @__PURE__ */ Object.freeze({ p: ["M13.48 3.63A8.5 8.5 0 1 1 9.09 4.01","M12 7.5V12l3 2"], n: [[13.48,3.63]] });
/** payout withdraw transfer bank */
export const payout: Glyph = /* @__PURE__ */ Object.freeze({ p: ["M5 9H19L21 11V18L19 20H5L3 18V11Z","M12 2.5v8","M8.5 7 12 10.5 15.5 7","M6.5 16.5h3"], n: [[16.5,16.5]] });
/** wallet balance credits money */
export const wallet: Glyph = /* @__PURE__ */ Object.freeze({ p: ["M17 7.5V5.5L15 4H6L4 6v12l2 2h13l1-1v-3","M4.5 7.5H19l1 1v3","M15.2 11.5H20.3L21.5 12.7V14.8L20.3 16H15.2L14 14.8V12.7Z"], n: [[17.3,13.75]] });
/** share revenue 90 percent creator split */
export const share90: Glyph = /* @__PURE__ */ Object.freeze({ p: ["M12 12.5L17 5.62A8.5 8.5 0 1 1 12 4Z","M12.9 9.8L12.9 1.8A8 8 0 0 1 17.6 3.33Z"], n: [[12,12.5]] });
/** private lock secure */
export const lock: Glyph = /* @__PURE__ */ Object.freeze({ p: ["M7 11H17L19 13V19L17 21H7L5 19V13Z","M8 11V7.5a4 4 0 0 1 8 0V11"], n: [[12,16]] });
/** follow subscribe add user */
export const follow: Glyph = /* @__PURE__ */ Object.freeze({ p: ["M10 4.3L13.64 6.4L13.64 10.6L10 12.7L6.36 10.6L6.36 6.4Z","M3 20.5c.9-3.3 3.7-5.2 7-5.2 1.5 0 2.9.4 4 1.1","M18.5 13v6M15.5 16h6"], n: [[10,8.5]] });
/** message chat dm conversation */
export const message: Glyph = /* @__PURE__ */ Object.freeze({ p: ["M6 4h12l2.5 2.5v8L18 17h-6.5L7 20.5V17H6l-2.5-2.5v-8z"], n: [[12,10.5]] });
/** upload publish send */
export const upload: Glyph = /* @__PURE__ */ Object.freeze({ p: ["M12 15.5V4","M7.5 8.5 12 4l4.5 4.5","M4 14.5v4l2 2h12l2-2v-4"], n: [[12,15.5]] });
/** video clip film */
export const video: Glyph = /* @__PURE__ */ Object.freeze({ p: ["M4.5 6H14L16 8V16L14 18H4.5L2.5 16V8Z","M16 10.5 21.5 7.5v9L16 13.5"], n: [[9.25,12]] });
/** play start */
export const play: Glyph = /* @__PURE__ */ Object.freeze({ p: ["M7.5 4.5v15l12-7.5z"] });
/** pause stop */
export const pause: Glyph = /* @__PURE__ */ Object.freeze({ p: ["M8 5v14M16 5v14"] });
/** image photo picture media */
export const image: Glyph = /* @__PURE__ */ Object.freeze({ p: ["M5.5 4H18.5L21 6.5V17.5L18.5 20H5.5L3 17.5V6.5Z","M3.5 17 9 11.5l4 4 2.5-2.5 5 5"], n: [[15.5,8.5]] });
/** like love favourite */
export const heart: Glyph = /* @__PURE__ */ Object.freeze({ p: ["M12 20 4.2 12.2a4.6 4.6 0 0 1 6.5-6.5L12 7l1.3-1.3a4.6 4.6 0 0 1 6.5 6.5z"], n: [[12,12]] });
/** sovereign ai chat assistant conversation */
export const chat: Glyph = /* @__PURE__ */ Object.freeze({ p: ["M4 5.5 5.5 4h13L20 5.5v9L18.5 16H11l-4.5 4v-4h-1L4 14.5z","M8 8.5h8M8 11.5h5"], n: [[16,11.5]] });
/** ai spark sovereign model intelligence */
export const ai: Glyph = /* @__PURE__ */ Object.freeze({ p: ["M11 3.5 12.6 8.4 17.5 10 12.6 11.6 11 16.5 9.4 11.6 4.5 10 9.4 8.4z","M18 15v5M15.5 17.5h5"], n: [[11,10]] });
/** agent bot automation assistant */
export const agent: Glyph = /* @__PURE__ */ Object.freeze({ p: ["M7 8H17L19.5 10.5V17.5L17 20H7L4.5 17.5V10.5Z","M12 8V4.5","M2 13v3M22 13v3","M9.5 16.5h5"], c: [[9.25,12.5,1.1],[14.75,12.5,1.1]], n: [[12,3.6]] });
/** studio workshop build editor */
export const studio: Glyph = /* @__PURE__ */ Object.freeze({ p: ["M5.5 4H18.5L21 6.5V17.5L18.5 20H5.5L3 17.5V6.5Z","M3 9h18","M9 9v11"], n: [[15,14.5]] });
/** pack bundle package module */
export const pack: Glyph = /* @__PURE__ */ Object.freeze({ p: ["M12 3L19.79 7.5L19.79 16.5L12 21L4.21 16.5L4.21 7.5Z","M12 21v-9","M4.2 7.5 12 12l7.8-4.5"], n: [[12,12]] });
/** automation workflow flow trigger */
export const automation: Glyph = /* @__PURE__ */ Object.freeze({ p: ["M4.5 3H8.5L10 4.5V8.5L8.5 10H4.5L3 8.5V4.5Z","M15.5 14H19.5L21 15.5V19.5L19.5 21H15.5L14 19.5V15.5Z","M6.5 10v4.5l2 2H14","M17.5 14V9.5l-2-2H10"], n: [[17.5,17.5]] });
/** knowledge documents rag library book */
export const knowledge: Glyph = /* @__PURE__ */ Object.freeze({ p: ["M4 5.5 5.5 4H11l1 1.5L13 4h5.5L20 5.5v13H13l-1 1.5-1-1.5H4z","M12 5.5v13"], n: [[16.5,9]] });
/** privacy shield security sovereign protect */
export const shield: Glyph = /* @__PURE__ */ Object.freeze({ p: ["M12 2.8 19.5 6v5.5c0 4.6-3.2 8.3-7.5 9.7-4.3-1.4-7.5-5.1-7.5-9.7V6z"], n: [[12,11.5]] });
/** local device laptop on-premise offline */
export const local: Glyph = /* @__PURE__ */ Object.freeze({ p: ["M6.3 4.5H17.7L19.5 6.3V13.2L17.7 15H6.3L4.5 13.2V6.3Z","M2 19.5h20","M4.5 15 3 18M19.5 15l1.5 3"], n: [[12,9.75]] });
/** server self-hosted infrastructure node */
export const server: Glyph = /* @__PURE__ */ Object.freeze({ p: ["M5.3 3.5H18.7L20.5 5.3V8.7L18.7 10.5H5.3L3.5 8.7V5.3Z","M5.3 13.5H18.7L20.5 15.3V18.7L18.7 20.5H5.3L3.5 18.7V15.3Z","M7 7h4M7 17h4"], n: [[16.5,17]] });
/** billing invoice receipt */
export const billing: Glyph = /* @__PURE__ */ Object.freeze({ p: ["M5 3.5h14v17l-2.3-1.5-2.4 1.5-2.3-1.5-2.3 1.5-2.4-1.5L5 20.5z","M8.5 8h7M8.5 11.5h7M8.5 15h3.5"], n: [[15.5,15]] });
/** credits coins tokens balance */
export const credits: Glyph = /* @__PURE__ */ Object.freeze({ p: ["M9.5 3.5L15.13 6.75L15.13 13.25L9.5 16.5L3.87 13.25L3.87 6.75Z","M14.6 6.3a6.5 6.5 0 0 1 2.4 12.6 6.5 6.5 0 0 1-5.3-.4"], n: [[9.5,10]] });
/** theme appearance dark light contrast */
export const theme: Glyph = /* @__PURE__ */ Object.freeze({ p: ["M12 3.5v17","M12 3.5a8.5 8.5 0 0 1 0 17z"], c: [[12,12,8.5]] });
/** light mode sun */
export const sun: Glyph = /* @__PURE__ */ Object.freeze({ p: ["M12 8L15.46 10L15.46 14L12 16L8.54 14L8.54 10Z","M12 2.5v2M12 19.5v2M2.5 12h2M19.5 12h2M5.3 5.3l1.4 1.4M17.3 17.3l1.4 1.4M5.3 18.7l1.4-1.4M17.3 6.7l1.4-1.4"], n: [[12,12]] });
/** dark mode moon night */
export const moon: Glyph = /* @__PURE__ */ Object.freeze({ p: ["M20 14.5A8.5 8.5 0 1 1 9.5 4a6.5 6.5 0 0 0 10.5 10.5z"], n: [[17,6]] });
/** search find magnifier */
export const search: Glyph = /* @__PURE__ */ Object.freeze({ p: ["M15.3 15.3 20.5 20.5"], c: [[10.5,10.5,6.5]], n: [[10.5,10.5]] });
/** settings preferences gear */
export const settings: Glyph = /* @__PURE__ */ Object.freeze({ p: ["M12 3.5L19.36 7.75L19.36 16.25L12 20.5L4.64 16.25L4.64 7.75Z","M12 3.5V7M12 17v3.5M4.6 7.75l3.05 1.75M16.35 14.5l3.05 1.75M4.6 16.25l3.05-1.75M16.35 9.5l3.05-1.75"], c: [[12,12,3]], n: [[12,12]] });
/** notification bell alert */
export const notification: Glyph = /* @__PURE__ */ Object.freeze({ p: ["M6 16.5V10a6 6 0 0 1 12 0v6.5l1.5 2h-15z","M10 21h4"], n: [[12,3]] });
/** user account person profile */
export const user: Glyph = /* @__PURE__ */ Object.freeze({ p: ["M4.5 20.5c1-3.5 4-5.5 7.5-5.5s6.5 2 7.5 5.5"], c: [[12,8.5,4]] });
/** users team group community */
export const users: Glyph = /* @__PURE__ */ Object.freeze({ p: ["M2.5 19.5c.8-3 3.3-4.8 6.5-4.8s5.7 1.8 6.5 4.8","M15.5 5.3a3.5 3.5 0 0 1 0 6.4","M17.5 14.9c2 .6 3.4 2.2 4 4.6"], c: [[9,8.5,3.5]] });
/** calendar date schedule */
export const calendar: Glyph = /* @__PURE__ */ Object.freeze({ p: ["M6 5H18L20.5 7.5V18L18 20.5H6L3.5 18V7.5Z","M3.5 10h17","M8 3v4M16 3v4"], n: [[15.5,15]] });
/** clock time duration */
export const clock: Glyph = /* @__PURE__ */ Object.freeze({ p: ["M12 7.5V12l3 2"], c: [[12,12,8.5]] });
/** globe language web public */
export const globe: Glyph = /* @__PURE__ */ Object.freeze({ p: ["M3.5 12h17","M12 3.5c2.3 2.4 3.5 5.2 3.5 8.5s-1.2 6.1-3.5 8.5c-2.3-2.4-3.5-5.2-3.5-8.5S9.7 5.9 12 3.5z"], c: [[12,12,8.5]] });
/** show visible view */
export const eye: Glyph = /* @__PURE__ */ Object.freeze({ p: ["M2.5 12C4.6 8 8 6 12 6s7.4 2 9.5 6c-2.1 4-5.5 6-9.5 6s-7.4-2-9.5-6z"], c: [[12,12,3]] });
/** hide hidden invisible */
export const eyeOff: Glyph = /* @__PURE__ */ Object.freeze({ p: ["M9.9 6.3A9.9 9.9 0 0 1 12 6c4 0 7.4 2 9.5 6a12.7 12.7 0 0 1-2.4 3.2","M6.6 7.6A11.3 11.3 0 0 0 2.5 12c2.1 4 5.5 6 9.5 6 1.7 0 3.3-.4 4.7-1.1","M10 10a3 3 0 0 0 4.2 4.2","M3 3l18 18"] });
/** info information help */
export const info: Glyph = /* @__PURE__ */ Object.freeze({ p: ["M12 3L19.79 7.5L19.79 16.5L12 21L4.21 16.5L4.21 7.5Z","M12 11v5.5"], n: [[12,7.8]] });
/** warning alert caution */
export const warning: Glyph = /* @__PURE__ */ Object.freeze({ p: ["M12 3.5 21 19.5H3z","M12 9.5v5"], n: [[12,17]] });
/** home start dashboard */
export const home: Glyph = /* @__PURE__ */ Object.freeze({ p: ["M3.5 10.5 12 3.5l8.5 7v8.5L19 20.5H5L3.5 19z","M9.5 20.5v-5.5h5v5.5"] });
/** menu hamburger navigation */
export const menu: Glyph = /* @__PURE__ */ Object.freeze({ p: ["M4 7h16M4 12h16M4 17h10"] });
/** close dismiss x cancel */
export const close: Glyph = /* @__PURE__ */ Object.freeze({ p: ["M6 6l12 12M18 6 6 18"] });
/** back arrow left previous */
export const back: Glyph = /* @__PURE__ */ Object.freeze({ p: ["M20 12H4.5","M10.5 6 4.5 12l6 6"] });
/** forward arrow right next */
export const forward: Glyph = /* @__PURE__ */ Object.freeze({ p: ["M4 12h15.5","M13.5 6l6 6-6 6"] });
/** chevron down expand */
export const chevronDown: Glyph = /* @__PURE__ */ Object.freeze({ p: ["M6 9.5l6 6 6-6"] });
/** chevron right open */
export const chevronRight: Glyph = /* @__PURE__ */ Object.freeze({ p: ["M9.5 6l6 6-6 6"] });
/** plus add create new */
export const plus: Glyph = /* @__PURE__ */ Object.freeze({ p: ["M12 4.5v15M4.5 12h15"] });
/** check done valid */
export const check: Glyph = /* @__PURE__ */ Object.freeze({ p: ["M4.5 12.5l5 5L19.5 7"] });
/** more options ellipsis */
export const more: Glyph = /* @__PURE__ */ Object.freeze({ n: [[5.5,12],[12,12],[18.5,12]] });
/** external open new window link */
export const external: Glyph = /* @__PURE__ */ Object.freeze({ p: ["M13.5 3.5h7v7","M20.5 3.5 11 13","M18 14v4.5L16.5 20h-11L4 18.5v-11L5.5 6H10"] });
/** link url chain */
export const link: Glyph = /* @__PURE__ */ Object.freeze({ p: ["M10 14a4 4 0 0 0 5.7 0l3.6-3.6a4 4 0 0 0-5.7-5.7L12 6.3","M14 10a4 4 0 0 0-5.7 0l-3.6 3.6a4 4 0 0 0 5.7 5.7l1.6-1.6"] });
/** filter funnel sort */
export const filter: Glyph = /* @__PURE__ */ Object.freeze({ p: ["M3.5 5h17l-6.5 7.5V19l-4 1.5v-8z"] });
/** edit pencil write */
export const edit: Glyph = /* @__PURE__ */ Object.freeze({ p: ["M4 20h4L19 9l-4-4L4 16z","M13 7l4 4"] });
/** delete trash remove */
export const trash: Glyph = /* @__PURE__ */ Object.freeze({ p: ["M3.5 6.5h17","M9 6.5V4h6v2.5","M5.5 6.5l1 12.5 1.5 1.5h8l1.5-1.5 1-12.5","M10 10.5v6M14 10.5v6"] });
/** copy duplicate clipboard */
export const copy: Glyph = /* @__PURE__ */ Object.freeze({ p: ["M10.5 8.5H18.5L20.5 10.5V18.5L18.5 20.5H10.5L8.5 18.5V10.5Z","M15.5 8.5V5L14 3.5H5L3.5 5v9L5 15.5h3.5"] });
/** download save export */
export const download: Glyph = /* @__PURE__ */ Object.freeze({ p: ["M12 4v11.5","M7.5 11 12 15.5l4.5-4.5","M4 14.5v4l2 2h12l2-2v-4"] });
/** logout sign out exit */
export const logout: Glyph = /* @__PURE__ */ Object.freeze({ p: ["M10 4H5.5L4 5.5v13L5.5 20H10","M9.5 12h11","M16.5 8l4 4-4 4"] });
/** bookmark save later */
export const bookmark: Glyph = /* @__PURE__ */ Object.freeze({ p: ["M6 3.5h12v17l-6-4.5-6 4.5z"] });
/** sound volume audio unmute speaker */
export const sound: Glyph = /* @__PURE__ */ Object.freeze({ p: ["M3.5 9.5H7l5-4.5v14l-5-4.5H3.5z","M15.5 9a4.2 4.2 0 0 1 0 6","M18.3 6.3a8.2 8.2 0 0 1 0 11.4"] });
/** mute sound off silent volume speaker */
export const mute: Glyph = /* @__PURE__ */ Object.freeze({ p: ["M3.5 9.5H7l5-4.5v14l-5-4.5H3.5z","M16 9.5l5 5M21 9.5l-5 5"] });
/** flag report abuse moderation */
export const flag: Glyph = /* @__PURE__ */ Object.freeze({ p: ["M5 21V3.5","M5 4.5c2.3-1.4 4.7-1.4 7 0s4.7 1.4 7 0v8.5c-2.3 1.4-4.7 1.4-7 0s-4.7-1.4-7 0"] });

/** Every glyph's name, its group and its keywords — for catalogues and search (not for the components). */
export const glyphIndex = {
  "tip": {
    "component": "TipIcon",
    "group": "product",
    "keywords": "tip gift support creator"
  },
  "unlock": {
    "component": "UnlockIcon",
    "group": "product",
    "keywords": "unlock open paid content"
  },
  "paid": {
    "component": "PaidIcon",
    "group": "product",
    "keywords": "paid premium ticket pass access"
  },
  "auction": {
    "component": "AuctionIcon",
    "group": "product",
    "keywords": "auction gavel bid escrow"
  },
  "challenge": {
    "component": "ChallengeIcon",
    "group": "product",
    "keywords": "challenge dare flag"
  },
  "goal": {
    "component": "GoalIcon",
    "group": "product",
    "keywords": "goal target objective"
  },
  "creator": {
    "component": "CreatorIcon",
    "group": "product",
    "keywords": "creator profile star user"
  },
  "story": {
    "component": "StoryIcon",
    "group": "product",
    "keywords": "story ring circle"
  },
  "story24h": {
    "component": "Story24hIcon",
    "group": "product",
    "keywords": "story 24h ephemeral clock expires"
  },
  "payout": {
    "component": "PayoutIcon",
    "group": "product",
    "keywords": "payout withdraw transfer bank"
  },
  "wallet": {
    "component": "WalletIcon",
    "group": "product",
    "keywords": "wallet balance credits money"
  },
  "share90": {
    "component": "Share90Icon",
    "group": "product",
    "keywords": "share revenue 90 percent creator split"
  },
  "lock": {
    "component": "LockIcon",
    "group": "product",
    "keywords": "private lock secure"
  },
  "follow": {
    "component": "FollowIcon",
    "group": "product",
    "keywords": "follow subscribe add user"
  },
  "message": {
    "component": "MessageIcon",
    "group": "product",
    "keywords": "message chat dm conversation"
  },
  "upload": {
    "component": "UploadIcon",
    "group": "product",
    "keywords": "upload publish send"
  },
  "video": {
    "component": "VideoIcon",
    "group": "product",
    "keywords": "video clip film"
  },
  "play": {
    "component": "PlayIcon",
    "group": "interface",
    "keywords": "play start"
  },
  "pause": {
    "component": "PauseIcon",
    "group": "interface",
    "keywords": "pause stop"
  },
  "image": {
    "component": "ImageIcon",
    "group": "product",
    "keywords": "image photo picture media"
  },
  "heart": {
    "component": "HeartIcon",
    "group": "product",
    "keywords": "like love favourite"
  },
  "chat": {
    "component": "ChatIcon",
    "group": "product",
    "keywords": "sovereign ai chat assistant conversation"
  },
  "ai": {
    "component": "AiIcon",
    "group": "product",
    "keywords": "ai spark sovereign model intelligence"
  },
  "agent": {
    "component": "AgentIcon",
    "group": "product",
    "keywords": "agent bot automation assistant"
  },
  "studio": {
    "component": "StudioIcon",
    "group": "product",
    "keywords": "studio workshop build editor"
  },
  "pack": {
    "component": "PackIcon",
    "group": "product",
    "keywords": "pack bundle package module"
  },
  "automation": {
    "component": "AutomationIcon",
    "group": "product",
    "keywords": "automation workflow flow trigger"
  },
  "knowledge": {
    "component": "KnowledgeIcon",
    "group": "product",
    "keywords": "knowledge documents rag library book"
  },
  "shield": {
    "component": "ShieldIcon",
    "group": "product",
    "keywords": "privacy shield security sovereign protect"
  },
  "local": {
    "component": "LocalIcon",
    "group": "product",
    "keywords": "local device laptop on-premise offline"
  },
  "server": {
    "component": "ServerIcon",
    "group": "product",
    "keywords": "server self-hosted infrastructure node"
  },
  "billing": {
    "component": "BillingIcon",
    "group": "product",
    "keywords": "billing invoice receipt"
  },
  "credits": {
    "component": "CreditsIcon",
    "group": "product",
    "keywords": "credits coins tokens balance"
  },
  "theme": {
    "component": "ThemeIcon",
    "group": "system",
    "keywords": "theme appearance dark light contrast"
  },
  "sun": {
    "component": "SunIcon",
    "group": "system",
    "keywords": "light mode sun"
  },
  "moon": {
    "component": "MoonIcon",
    "group": "system",
    "keywords": "dark mode moon night"
  },
  "search": {
    "component": "SearchIcon",
    "group": "system",
    "keywords": "search find magnifier"
  },
  "settings": {
    "component": "SettingsIcon",
    "group": "system",
    "keywords": "settings preferences gear"
  },
  "notification": {
    "component": "NotificationIcon",
    "group": "system",
    "keywords": "notification bell alert"
  },
  "user": {
    "component": "UserIcon",
    "group": "system",
    "keywords": "user account person profile"
  },
  "users": {
    "component": "UsersIcon",
    "group": "system",
    "keywords": "users team group community"
  },
  "calendar": {
    "component": "CalendarIcon",
    "group": "system",
    "keywords": "calendar date schedule"
  },
  "clock": {
    "component": "ClockIcon",
    "group": "system",
    "keywords": "clock time duration"
  },
  "globe": {
    "component": "GlobeIcon",
    "group": "system",
    "keywords": "globe language web public"
  },
  "eye": {
    "component": "EyeIcon",
    "group": "system",
    "keywords": "show visible view"
  },
  "eyeOff": {
    "component": "EyeOffIcon",
    "group": "system",
    "keywords": "hide hidden invisible"
  },
  "info": {
    "component": "InfoIcon",
    "group": "system",
    "keywords": "info information help"
  },
  "warning": {
    "component": "WarningIcon",
    "group": "system",
    "keywords": "warning alert caution"
  },
  "home": {
    "component": "HomeIcon",
    "group": "interface",
    "keywords": "home start dashboard"
  },
  "menu": {
    "component": "MenuIcon",
    "group": "interface",
    "keywords": "menu hamburger navigation"
  },
  "close": {
    "component": "CloseIcon",
    "group": "interface",
    "keywords": "close dismiss x cancel"
  },
  "back": {
    "component": "BackIcon",
    "group": "interface",
    "keywords": "back arrow left previous"
  },
  "forward": {
    "component": "ForwardIcon",
    "group": "interface",
    "keywords": "forward arrow right next"
  },
  "chevronDown": {
    "component": "ChevronDownIcon",
    "group": "interface",
    "keywords": "chevron down expand"
  },
  "chevronRight": {
    "component": "ChevronRightIcon",
    "group": "interface",
    "keywords": "chevron right open"
  },
  "plus": {
    "component": "PlusIcon",
    "group": "interface",
    "keywords": "plus add create new"
  },
  "check": {
    "component": "CheckIcon",
    "group": "interface",
    "keywords": "check done valid"
  },
  "more": {
    "component": "MoreIcon",
    "group": "interface",
    "keywords": "more options ellipsis"
  },
  "external": {
    "component": "ExternalIcon",
    "group": "interface",
    "keywords": "external open new window link"
  },
  "link": {
    "component": "LinkIcon",
    "group": "interface",
    "keywords": "link url chain"
  },
  "filter": {
    "component": "FilterIcon",
    "group": "interface",
    "keywords": "filter funnel sort"
  },
  "edit": {
    "component": "EditIcon",
    "group": "interface",
    "keywords": "edit pencil write"
  },
  "trash": {
    "component": "TrashIcon",
    "group": "interface",
    "keywords": "delete trash remove"
  },
  "copy": {
    "component": "CopyIcon",
    "group": "interface",
    "keywords": "copy duplicate clipboard"
  },
  "download": {
    "component": "DownloadIcon",
    "group": "interface",
    "keywords": "download save export"
  },
  "logout": {
    "component": "LogoutIcon",
    "group": "interface",
    "keywords": "logout sign out exit"
  },
  "bookmark": {
    "component": "BookmarkIcon",
    "group": "interface",
    "keywords": "bookmark save later"
  },
  "sound": {
    "component": "SoundIcon",
    "group": "interface",
    "keywords": "sound volume audio unmute speaker"
  },
  "mute": {
    "component": "MuteIcon",
    "group": "interface",
    "keywords": "mute sound off silent volume speaker"
  },
  "flag": {
    "component": "FlagIcon",
    "group": "interface",
    "keywords": "flag report abuse moderation"
  }
} as const;
