// GENERATED by scripts/glyphs.mjs — do not edit.
import { createIcon } from "./create-icon";
import * as g from "./glyphs";

/** tip gift support creator */
export const TipIcon = /* @__PURE__ */ createIcon("TipIcon", g.tip);
/** unlock open paid content */
export const UnlockIcon = /* @__PURE__ */ createIcon("UnlockIcon", g.unlock);
/** paid premium ticket pass access */
export const PaidIcon = /* @__PURE__ */ createIcon("PaidIcon", g.paid);
/** auction gavel bid escrow */
export const AuctionIcon = /* @__PURE__ */ createIcon("AuctionIcon", g.auction);
/** challenge dare flag */
export const ChallengeIcon = /* @__PURE__ */ createIcon("ChallengeIcon", g.challenge);
/** goal target objective */
export const GoalIcon = /* @__PURE__ */ createIcon("GoalIcon", g.goal);
/** creator profile star user */
export const CreatorIcon = /* @__PURE__ */ createIcon("CreatorIcon", g.creator);
/** story ring circle */
export const StoryIcon = /* @__PURE__ */ createIcon("StoryIcon", g.story);
/** story 24h ephemeral clock expires */
export const Story24hIcon = /* @__PURE__ */ createIcon("Story24hIcon", g.story24h);
/** payout withdraw transfer bank */
export const PayoutIcon = /* @__PURE__ */ createIcon("PayoutIcon", g.payout);
/** wallet balance credits money */
export const WalletIcon = /* @__PURE__ */ createIcon("WalletIcon", g.wallet);
/** share revenue 90 percent creator split */
export const Share90Icon = /* @__PURE__ */ createIcon("Share90Icon", g.share90);
/** private lock secure */
export const LockIcon = /* @__PURE__ */ createIcon("LockIcon", g.lock);
/** follow subscribe add user */
export const FollowIcon = /* @__PURE__ */ createIcon("FollowIcon", g.follow);
/** message chat dm conversation */
export const MessageIcon = /* @__PURE__ */ createIcon("MessageIcon", g.message);
/** upload publish send */
export const UploadIcon = /* @__PURE__ */ createIcon("UploadIcon", g.upload);
/** video clip film */
export const VideoIcon = /* @__PURE__ */ createIcon("VideoIcon", g.video);
/** play start */
export const PlayIcon = /* @__PURE__ */ createIcon("PlayIcon", g.play);
/** pause stop */
export const PauseIcon = /* @__PURE__ */ createIcon("PauseIcon", g.pause);
/** image photo picture media */
export const ImageIcon = /* @__PURE__ */ createIcon("ImageIcon", g.image);
/** like love favourite */
export const HeartIcon = /* @__PURE__ */ createIcon("HeartIcon", g.heart);
/** sovereign ai chat assistant conversation */
export const ChatIcon = /* @__PURE__ */ createIcon("ChatIcon", g.chat);
/** ai spark sovereign model intelligence */
export const AiIcon = /* @__PURE__ */ createIcon("AiIcon", g.ai);
/** agent bot automation assistant */
export const AgentIcon = /* @__PURE__ */ createIcon("AgentIcon", g.agent);
/** studio workshop build editor */
export const StudioIcon = /* @__PURE__ */ createIcon("StudioIcon", g.studio);
/** pack bundle package module */
export const PackIcon = /* @__PURE__ */ createIcon("PackIcon", g.pack);
/** automation workflow flow trigger */
export const AutomationIcon = /* @__PURE__ */ createIcon("AutomationIcon", g.automation);
/** knowledge documents rag library book */
export const KnowledgeIcon = /* @__PURE__ */ createIcon("KnowledgeIcon", g.knowledge);
/** privacy shield security sovereign protect */
export const ShieldIcon = /* @__PURE__ */ createIcon("ShieldIcon", g.shield);
/** local device laptop on-premise offline */
export const LocalIcon = /* @__PURE__ */ createIcon("LocalIcon", g.local);
/** server self-hosted infrastructure node */
export const ServerIcon = /* @__PURE__ */ createIcon("ServerIcon", g.server);
/** billing invoice receipt */
export const BillingIcon = /* @__PURE__ */ createIcon("BillingIcon", g.billing);
/** credits coins tokens balance */
export const CreditsIcon = /* @__PURE__ */ createIcon("CreditsIcon", g.credits);
/** theme appearance dark light contrast */
export const ThemeIcon = /* @__PURE__ */ createIcon("ThemeIcon", g.theme);
/** light mode sun */
export const SunIcon = /* @__PURE__ */ createIcon("SunIcon", g.sun);
/** dark mode moon night */
export const MoonIcon = /* @__PURE__ */ createIcon("MoonIcon", g.moon);
/** search find magnifier */
export const SearchIcon = /* @__PURE__ */ createIcon("SearchIcon", g.search);
/** settings preferences gear */
export const SettingsIcon = /* @__PURE__ */ createIcon("SettingsIcon", g.settings);
/** notification bell alert */
export const NotificationIcon = /* @__PURE__ */ createIcon("NotificationIcon", g.notification);
/** user account person profile */
export const UserIcon = /* @__PURE__ */ createIcon("UserIcon", g.user);
/** users team group community */
export const UsersIcon = /* @__PURE__ */ createIcon("UsersIcon", g.users);
/** calendar date schedule */
export const CalendarIcon = /* @__PURE__ */ createIcon("CalendarIcon", g.calendar);
/** clock time duration */
export const ClockIcon = /* @__PURE__ */ createIcon("ClockIcon", g.clock);
/** globe language web public */
export const GlobeIcon = /* @__PURE__ */ createIcon("GlobeIcon", g.globe);
/** show visible view */
export const EyeIcon = /* @__PURE__ */ createIcon("EyeIcon", g.eye);
/** hide hidden invisible */
export const EyeOffIcon = /* @__PURE__ */ createIcon("EyeOffIcon", g.eyeOff);
/** info information help */
export const InfoIcon = /* @__PURE__ */ createIcon("InfoIcon", g.info);
/** warning alert caution */
export const WarningIcon = /* @__PURE__ */ createIcon("WarningIcon", g.warning);
/** home start dashboard */
export const HomeIcon = /* @__PURE__ */ createIcon("HomeIcon", g.home);
/** menu hamburger navigation */
export const MenuIcon = /* @__PURE__ */ createIcon("MenuIcon", g.menu);
/** close dismiss x cancel */
export const CloseIcon = /* @__PURE__ */ createIcon("CloseIcon", g.close);
/** back arrow left previous */
export const BackIcon = /* @__PURE__ */ createIcon("BackIcon", g.back);
/** forward arrow right next */
export const ForwardIcon = /* @__PURE__ */ createIcon("ForwardIcon", g.forward);
/** chevron down expand */
export const ChevronDownIcon = /* @__PURE__ */ createIcon("ChevronDownIcon", g.chevronDown);
/** chevron right open */
export const ChevronRightIcon = /* @__PURE__ */ createIcon("ChevronRightIcon", g.chevronRight);
/** plus add create new */
export const PlusIcon = /* @__PURE__ */ createIcon("PlusIcon", g.plus);
/** check done valid */
export const CheckIcon = /* @__PURE__ */ createIcon("CheckIcon", g.check);
/** more options ellipsis */
export const MoreIcon = /* @__PURE__ */ createIcon("MoreIcon", g.more);
/** external open new window link */
export const ExternalIcon = /* @__PURE__ */ createIcon("ExternalIcon", g.external);
/** link url chain */
export const LinkIcon = /* @__PURE__ */ createIcon("LinkIcon", g.link);
/** filter funnel sort */
export const FilterIcon = /* @__PURE__ */ createIcon("FilterIcon", g.filter);
/** edit pencil write */
export const EditIcon = /* @__PURE__ */ createIcon("EditIcon", g.edit);
/** delete trash remove */
export const TrashIcon = /* @__PURE__ */ createIcon("TrashIcon", g.trash);
/** copy duplicate clipboard */
export const CopyIcon = /* @__PURE__ */ createIcon("CopyIcon", g.copy);
/** download save export */
export const DownloadIcon = /* @__PURE__ */ createIcon("DownloadIcon", g.download);
/** logout sign out exit */
export const LogoutIcon = /* @__PURE__ */ createIcon("LogoutIcon", g.logout);
/** bookmark save later */
export const BookmarkIcon = /* @__PURE__ */ createIcon("BookmarkIcon", g.bookmark);
